-- ============================================================
-- Teardown — Remove all FitLife objects
-- ============================================================
USE ROLE ACCOUNTADMIN;

DROP SERVICE IF EXISTS FITLIFE_MEMBERS.PUBLIC.REACT_FITLIFE_APP;
DROP AGENT IF EXISTS FITLIFE_MEMBERS.PUBLIC.FITLIFE_AGENT;
DROP SEMANTIC VIEW IF EXISTS FITLIFE_MEMBERS.PUBLIC.FITLIFE_SEGMENTATION;
DROP TABLE IF EXISTS FITLIFE_MEMBERS.PUBLIC.VISITS;
DROP TABLE IF EXISTS FITLIFE_MEMBERS.PUBLIC.MEMBERS;
DROP EXTERNAL ACCESS INTEGRATION IF EXISTS FITLIFE_REACT_APP_EGRESS_EAI;
DROP COMPUTE POOL IF EXISTS FITLIFE_POOL_CPU;
DROP DATABASE IF EXISTS FITLIFE_MEMBERS;
