-- ============================================================
-- Teardown — Remove all objects
-- ============================================================
USE ROLE ACCOUNTADMIN;

DROP SERVICE IF EXISTS ONEDATA_AUDIENCE.PUBLIC.REACT_AUDIENCE_APP;
DROP AGENT IF EXISTS ONEDATA_AUDIENCE.PUBLIC.AUDIENCE_AGENT;
DROP SEMANTIC VIEW IF EXISTS ONEDATA_AUDIENCE.PUBLIC.AUDIENCE_SEGMENTATION;
DROP TABLE IF EXISTS ONEDATA_AUDIENCE.PUBLIC.TRANSACTIONS;
DROP TABLE IF EXISTS ONEDATA_AUDIENCE.PUBLIC.CUSTOMERS;
DROP COMPUTE POOL IF EXISTS DEMO_POOL_CPU;
DROP DATABASE IF EXISTS ONEDATA_AUDIENCE;
